export class CartaDTO {
    constructor(
        public id?: number,
        public nomeMembro?: string,
        public situacaoEspiritual?: string,
        public abreviaturaMin?: string,
        public statusMembro?: string, //situacaoCadastral
        public cartaoMembro?: string,
        public cartaoConjuge?: string,
        public membroDesde?: string,
        public tituloMin?: string,
        public tituloMin2?: string,      
        public nomeResponsavel?: string,
        public cargoResponsavel?: string,
        public tituloResponsavel?: string,
        public abreviaturaMinResponsavel?: string,
        public nomeSecretario?: string,
        public contatoSecretarioEscrevente?: string,
        public conjuge?: string,
        public sexo?: string,
        public conteudo?: string,
        public dataEmissao?: string,
        public dataValidade?: string,
        public cidadeDestino?: string,
        public idCidadeDestino?: string,
        public estadoDestino?: string,
        public ufDestino?: string,
        public paisDestino?: string,
        public siglaPais?: string,
        public observacao?: string,
        public tipoCarta?: string,
        public congregacaoDestino?: string,
        public igrejaLocal?: string,
        public cidadeLocal?: string,
        public ufLocal?: string,
        public modeloCarta?: string,
        public filho1?: string,
        public filho2?: string,
        public filho3?: string,
        public filho4?: string,
        public esposa?: boolean,
        public territorial?: boolean, 
        public estadual?: boolean,  
        public familia?: boolean,
        public filho?: boolean,
        public unica?: boolean,
        public pessoaId?: number,
        public idPaisDestino?: number,
        public idEstadoDestino?: number,
        public idConjuge?: number,
        public tipoCartaId?: number,
        public idResponsavel?: number,
        public idSecretario?: number,
        public qtde?: number,
        public modeloDocumentoId?: number,
        public igrejaId?: number,
        public idFilho1?: number,
        public idFilho2?: number,
        public idFilho3?: number,
        public idFilho4?: number,

        ){

        }
 }
